import type { Metadata } from "next";

import "./globals.css";   

import Hero from "@/components/Hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
    
        {children}
        <Hero/>
      </body>
    </html>
  );
}
